name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    required: false
    description: "The chart-releaser version to use (default: v1.2.1)"
  config:
    required: false
    description: "The relative path to the chart-releaser config file"
  charts_dir:
    required: false
    description: The charts directory
    default: charts
  charts_repo_url:
    required: false
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
  pages_branch:
    required: false
    description: GitHub pages branch to publish the index file
    default: gh-pages
runs:
  using: composite
  steps:
    - run: |
        owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
        repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")

        args=(--owner "$owner" --repo "$repo")
        args+=(--charts-dir "${{ inputs.charts_dir }}")

        if [[ -n "${{ inputs.version }}" ]]; then
            args+=(--version "${{ inputs.version }}")
        fi

        if [[ -n "${{ inputs.config }}" ]]; then
            args+=(--config "${{ inputs.config }}")
        fi

        if [[ -n "${{ inputs.charts_repo_url }}" ]]; then
            args+=(--charts-repo-url "${{ inputs.charts_repo_url }}")
        fi

        if [[ -n "${{ inputs.pages_branch }}" ]]; then
            args+=(--pages-branch "${{ inputs.pages_branch }}")
        fi

        "$GITHUB_ACTION_PATH/cr.sh" "${args[@]}"
      shell: bash
